toggle_session:
  name: Toggle charger session
  description: Start/stop a charging session
  target:
    entity:
      integration: shell_recharge
      # Home Assistant does not support filtering on custom features
      supported_features:
        - climate.ClimateEntityFeature.TARGET_TEMPERATURE
      #    - shell_recharge.ShellRechargeEntityFeature.TOGGLE_SESSION
  fields:
    card:
      name: Card
      description: Charge card to use for the session
      required: True
      selector:
        entity:
          filter:
            integration: shell_recharge
            #supported_features:
            #  - climate.ClimateEntityFeature.TARGET_TEMPERATURE
            #  - shell_recharge.ShellRechargeEntityFeature.PAY_FOR_ELECTRICITY
    toggle:
      name: Action
      description: Whether you want to stop or start a session
      example: start
      default: start
      required: True
      selector:
        select:
          options:
            - start
            - stop
